---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sabnzbd
spec:
  components:
    - ../../../../components/gatus/guarded
    - ../../../../components/keda/nfs-scaler
    - ../../../../components/volsync
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: ./kubernetes/apps/default/sabnzbd/app
  postBuild:
    substitute:
      APP: sabnzbd
      GATUS_SUBDOMAIN: sab
      VOLSYNC_CAPACITY: 1Gi
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
  wait: false
