---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kritika
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kritika-secret
    template:
      data:
        ADMIN_PASSWORD: "{{ .ADMIN_PASSWORD }}"
        GITHUB_APP_CLIENT_ID: "{{ .GITHUB_APP_CLIENT_ID }}"
        GITHUB_APP_PRIVATE_KEY: "{{ .GITHUB_APP_PRIVATE_KEY }}"
        GITHUB_APP_WEBHOOK_SECRET: "{{ .GITHUB_APP_WEBHOOK_SECRET }}"
        LITELLM_API_KEY: "{{ .LITELLM_API_KEY }}"
  dataFrom:
    - extract:
        key: kritika
