---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatus-sidecar
spec:
  chartRef:
    kind: OCIRepository
    name: gatus-sidecar
  interval: 1h
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: gatus-sidecar
            patch: |-
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: gatus-sidecar
              spec:
                strategy:
                  type: RollingUpdate
                  rollingUpdate:
                    maxSurge: 0
                    maxUnavailable: 1
  values:
    deploymentAnnotations:
      reloader.stakater.com/auto: "true"
    gatus:
      delayStartSeconds: "5"
      env:
        TZ: Pacific/Auckland
      image:
        digest: sha256:c5f210d095fa78e6efaa20ffeb14803f2ba4f10615e16a6d12087697149617f0
    sidecar:
      kinds:
        httproute:
          enable: true
          auto: true
        service:
          enable: true
    httpRoute:
      enabled: true
      annotations:
        gatus.home-operations.com/enabled: "false"
      hostnames:
        - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        - status.${SECRET_DOMAIN}
      parentRefs:
        - name: envoy-external
          namespace: network
    monitoring:
      serviceMonitor:
        enabled: true
    config:
      existingConfigMap: "{{ .Release.Name }}-configmap"
      items:
        - key: config.yaml
          path: config.yaml
    persistence:
      enabled: true
      storageClass: ceph-block
      accessMode: ReadWriteOnce
      size: 5Gi
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 512Mi
