---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-tunnel
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudflared-tunnel-secret
    template:
      data:
        CLOUDFLARE_TUNNEL_ID: "{{ .CLOUDFLARE_TUNNEL_ID }}"
        credentials.json: |
          {
            "AccountTag": "{{ .CLOUDFLARE_ACCOUNT_ID }}",
            "TunnelSecret": "{{ .CLOUDFLARE_TUNNEL_SECRET }}",
            "TunnelID": "{{ .CLOUDFLARE_TUNNEL_ID }}"
          }
  dataFrom:
    - extract:
        key: cloudflare
