[[remotes]]
git_url = "https://github.com/home-operations/.github"
ref = "main"
configs = ["lefthook.common.toml"]

[pre-commit.commands.mise-lock]
skip = true

[pre-commit.commands.format-yaml]
exclude = ["?*.sops.yaml", "?*.sops.yml"]
skip = true

[pre-commit.commands.format-oxfmt]
glob = ["*.yml", "*.yaml"]
run = "oxfmt {staged_files}"
exclude = ["?*.sops.yaml", "?*.sops.yml"]
stage_fixed = true
