[env]
# File paths
KUBECONFIG = '{{config_root}}/kubeconfig'
MINIJINJA_CONFIG_FILE = '{{config_root}}/.minijinja.toml'
SOPS_AGE_KEY_FILE = '{{config_root}}/age.key'
TALOSCONFIG = '{{config_root}}/talosconfig'
# Directory paths
ROOT_DIR = '{{config_root}}'
BOOTSTRAP_DIR = '{{config_root}}/bootstrap'
KUBERNETES_DIR = '{{config_root}}/kubernetes'
SCRIPTS_DIR = '{{config_root}}/scripts'
TALOS_DIR = '{{config_root}}/talos'
# Included file paths
_.file = [
  '{{env.KUBERNETES_DIR}}/apps/system-upgrade/versions.env'
]

[tools]
# NOTE: Keep the below versions pinned until Helm 3.18 can successfully pull charts that include a .prov file (provenance signature) as a separate OCI artifact layer
"helm" = "3.17.3"
"helmfile" = "1.0.0"
