---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age1vrlh74rr2ph4l7t07nhq0qmlwnm4ykckyhaf3teutxe437c6s4wsrf37mg"
stores:
  yaml:
    indent: 2
