---
- greeting:
    text: Homepage
    text_size: 2xl
- openmeteo:
    label: Home
    latitude: -36.8485
    longitude: 174.7633
    timezone: Pacific/Auckland
    units: metric
    cache: 5
    format:
      maximumFractionDigits: 1
- unifi_console:
    url: https://192.168.1.1
    key: "{{HOMEPAGE_VAR_UNIFI_API_KEY}}"
- datetime:
    text_size: xl
    format:
      dateStyle: long
      timeStyle: short
      hour12: false
