---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-external-dns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: external-external-dns-secret
    template:
      data:
        CF_API_TOKEN: "{{ .CLOUDFLARE_API_TOKEN }}"
  dataFrom:
    - extract:
        key: cloudflare
