# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:C36cO9mo0s3ZEe35O7zineflS0OUHqn8UWn6QRK4zIQa,iv:UQQ9Vm3yqnH/Nov/mOA/3Yq1zLdm6oHxm2l5xOosqmY=,tag:I+7LCplbkPkORck+vjQGxg==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:o73K2uMU32UagKexKH6f3yopFc0fzMoyYY+TNQ68gE6/6Rz2kQ==,iv:Jq6nH0umiohrS+pF61vVPoxDOLRhTNUnFt4RyuA8LRo=,tag:lMuotK439GVc9/qjYtjhsQ==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:xaTywvirLUm6SJAKr4NGnmjbwWt0Few=,iv:TcwlBHZ9eLrbNNZKb9xS2FOHAqCuBlT3aqBkLgv6KKw=,tag:QNjgYBkrGrQXlzCUhsmAjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13y77gw9dk0ersm563x0caw9j5vaa0uglhrd0u48n6frdkxwh5eus05t6x9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2cjVlN1o4aFdVUzlyaUt1
            aVhlenNQbklBTlRUbWVVWllQSTE2OFlCVVhvCmx0WkpxQlVvckRaTFEwaXBpUjIy
            Q3paMGZqWjdZYjVCOCtyTmt2K2YzR1EKLS0tIDQ1QnNBdU9XcmZhaGVGcEk1UWJE
            SDIxbUdNVnRmSkZiQUNHWWVjQW5lcVEK+cvLWbPd18M4ykOufaPFonl0xmnJzXTB
            uvTm+5GpVgO7hZFcr3wHJbTpwQeUbPbVo85F13PPUSA62Jx9CELUyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-16T06:26:15Z"
    mac: ENC[AES256_GCM,data:i4S1nBaAOv66CdMi1J8m8AHA7zLTrSo3qKLBzAtN6Ayita0Oq/mccC0qlZBp6a5p3Hr49vA6NtDQ9nXIblgMiUVH8Z1EJNpQm4F4+/+g/V/J2MCJKPHPBe1+/C+TAjrLpnZjBjcHenRh2Jdt1LOhVCic2xIFXK6yotO2p9hoQm8=,iv:y4L3JXp+prvL2SVaQmDsNvHizq/7GlUjbUwgnJEEy0A=,tag:N2RDzJUcTA1o8xOyZ6vPyA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
