apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:SyVcoCni/r6ceQmGAarfkhTNbG3tThwoCk9u8Tw0oZgSEote,iv:BA3zDgkoaWLFUS63v/ciWy2URJqsJPIxosG8/DyOIOI=,tag:ig3jc85l2WWjP9h5ErqLnQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:8FzaU74nmHAwZfhJuL13ALHSlwU0/flgqeygx8PMI3sWt42GDGgV2sCuk5sLkDpd3gM1mpPGMJS7VNippZrQwjEApeuu+j1NpBGmzxrnk34CIPLxIxXGueNbxFhVBedeExYUW+aX3EoCOejz5c4oek3O3h9HNTQ3pT/uZ831j7mcLmtIRzfUBpw559a+8JXtMd4RbfNO/7fM768Oy4S3PedMcdOm52ccomtQHaVNJA==,iv:/SAtXi65j+daC7yg0+oLVBnN0tRLLqWZHryoMYDI2v4=,tag:TMTV1XrrtfBYpFGydqwEZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mkv7d9mfplmlj46mxuvtzmfz2ds4q7620xszpu0vkzca6jjn3qcquck0cr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbnBaYjFqNnlidGlVN2xC
            ZEZiNisyRTZudzdCeXRYTkdTR1oxTTRhYVc4CnlMOHQvM0FMWlF2UU1BUGlMdUdB
            T0VBWTBmS1M3U1l2L0xZaGRCMERvYWMKLS0tIDBJU0lyWHp4OEJhSHpVN0h6c3U2
            QjNPV1NWVjNzUFNHaE5lb01GMlZmOVkK4nmSg+H1lGhIydsO9CZPDkQ1qs4rLd0W
            gpr4emB7YeGBjiNWU8pVBp5bQq3j2OT81HT1gL60T8R4o4HJOyp7Og==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-23T01:15:50Z"
    mac: ENC[AES256_GCM,data:Pu8ZFoGvoYEiw6Jyp+/jQq9CVSHy+33lCZOeh47Gmz23UrOLVN9ql9J/f5mrjzwTPN36Ln2gVWE9D/YGsRYhRxkWnfoNeOxZFTw4ZzqWNKwm4hq3g2KF89RR8pYZZkS1eDJJI1+l2uKvEdHaM2ZIJYFBj9EHeN97rsv+Bt4S3zE=,iv:bk0JSWvXv7JUM5tm3rPjknQ/jZu7tN0o7co4yqOG1X8=,tag:8Wkxt4312huuqor1RZqtmw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
