apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:abVfrAG85bw7hQe9DrFprVlEbp0ezezOiqPsNevDp9wOYxwf,iv:vIr8OhGgwXH/Pza6gRbZ9CvzgCRVYo//6Ik5euVxGcg=,tag:bAG6ss7Kk7FDPMSbi0N9cQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:xIKYkpGb6JjQvUEkY+DxG35v8H79a2IfJ/pCwzVowIcKocP2KeSI0H3rLnMiOWcF+rVaQxfjvYlzFw2lTO/FMch3bZkvlZcnRF+tqT84Cf20x8YlSjANdqk+YLqmEBdHr8mEHXIUW6etf2Y2OnGJFSFXaTTC4vVPubJBK8dBTXC5SbY6j9O69agnhtktapNp1DcTP3BQ5GM0BFrFrDa7OUBBpWKcbvzB2IDkamHoig==,iv:F+3PN7sSIXUVCcYjRJuI4WehUZJfjGhNY8VJOQ2bgvk=,tag:RH4EbyUxR3lJPUr6KC9+8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12pacd3s0eg20p7kd5459lflk8ahrw389um9zn7c5q3uexpny0phsqen4s3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZU9mVDFtK3lrNlR2Yy9j
            TDZiQ04zN2dNdGk5WTNabkl6Ujg5QlIrOVQ0CjltTkpXVGVVb0did0E3SDc2RVJ5
            WHhTV1RER2tOZmdySzFBSjVoK0U2RmsKLS0tIG9wSCtZcHlJU2J0Y0I5N0k2L0NP
            WWxnOWsxY29RMEpUVEhrQ1M0Y3FyTlkKJo4b4t9oHZjM31jrr8l6nfkYCRsbYr+0
            fRYAmwY5qbF8lz6aL1dN7Y7f22ci/ZHyGZvFV3c+l/O55TFnL/6iZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-12T01:02:59Z"
    mac: ENC[AES256_GCM,data:fBZ3jhB68qW0vw6LlpyT7zkmz/wHRZWpJqYDBGq1u+2AISZUG5Yw1qZUBSyQlWFA59YNsvaFh6UtSROzR4Npg0zlFliLyusVlPX/+8ZAv5e+ZhrYbyG7HfZKvIuqmibtiCDDSlmi4VZpXMDEK3iiC8hv5i+955/+2/BnnfKzEgg=,iv:EGqXSBtj5aaP8QIyj2d/x+TjF3/EWFHWiqJOxRoPsjY=,tag:itFEBn1CcEZG+T6HxyZwPw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
