apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:rO3vejgbEXoygs3u8+DAOxkK+3wECucuJV9FFDA/ZEjIUZkC,iv:5ErdFdg+LRj2J5TSHigyjpS0XdrZv0OfhOSitMDO8lY=,tag:It1bU7i9hfwJGRXUYrMTkQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:gIFK31sjCawNbCMen8/BJPLoVUFM5vMhdJqoGOBiAxbzntfqnylBjUcSjbym999KvLB81T86V+93h/OXXbZLzijkvGqx4yfuviZp3b8hpLJOYqmKulEWj8wESu7AxAky0mVNh/bgu1U5paNtelVhKp3PID2uCnmhshIm3jQPeoEMZjo0mzxj9nrV5adOenBBqhoabTU5vTOjeihgijX1tHii672c0jrKJRPrc/FbIw==,iv:CNZcu2dMafrOJRJ9Kif/iams52ZOoAewIfPm+XEQgT0=,tag:tnsvOGdZlZk31fryp3BViQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12pacd3s0eg20p7kd5459lflk8ahrw389um9zn7c5q3uexpny0phsqen4s3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2WEpNZ05TbDY5VnRwNWpU
            RVVPRDI5OVdvWnlkaVltT001aHBOaDNQZHcwCkF0SnZBUTNLM2huUEg2ZmRCTjRj
            aE9kLzF6UmtQLzVMaUZQL1NkQUQ0YVUKLS0tIHEwb2ZXckF6RWtqQ3VFWk5ZcERI
            WFNKR3FRc3BEcm5kcXFHTmViN2toSUUKqAEKITAzWcBDhve2fwYjnBR18XcpblBy
            SlRfWGWNbhwkjmxw05VihX1faw96zCmdNu8rizmWcYrWkm9wCqVgUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-05T04:35:06Z"
    mac: ENC[AES256_GCM,data:UxHmko4YQ7BRXhI6quW0aylVavzmZqWtwRLXkmc6kgLC+lptDwKw3OT6DmRsjT8xVo0VsFZBCgp/dEchsZYyfqfZeSbJXHH9+cglq8m3XReu2Sd3fYW2KgCKAKBHC9ozJCgkpYxCsH26ZQ2KcQfrS7Dzk0woxGt65lV3RXElOTc=,iv:89AZoPHDAdJmPb5qfV3WAneMV5adk26o0KsEgk5Huiw=,tag:JItGOEQsTauAMl+bKwpPvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
