---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cloudflare-dns-rules
spec:
  groups:
    - name: cloudflare-dns.rules
      rules:
        - alert: CloudflareDNSStale
          expr: |
            time() - external_dns_controller_last_sync_timestamp_seconds{job="cloudflare-dns"} > 60
          for: 5m
          annotations:
            summary: >-
              ExternalDNS controller ({{ $labels.job }}) has not synced in over 5 minutes.
          labels:
            severity: critical
