---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: litellm-db-secret
    template:
      data:
        DATABASE_URL: "postgresql://litellm:{{ .password }}@postgres-rw.database.svc.cluster.local:5432/litellm"
  dataFrom:
    - extract:
        key: litellm-db
