# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:M3ubraNvrm+Aiw3cZ9JfwTXvraRhRKl7qfwIKJNm5ZdU89xUbA==,iv:tl/GCk/XoHQFU0wbag91Zstst7YdQy2r3p40E1a/Nkc=,tag:6A2V1oZYNI2zf5F7aEhk8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13y77gw9dk0ersm563x0caw9j5vaa0uglhrd0u48n6frdkxwh5eus05t6x9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTjRHemNqSStFV0hVME02
            RE9yeGFqQ003em1mUW1wY25pK0UxRnJ6U0g0ClJqL2xsRzd1T3czN3FXRmdKc0JJ
            R1kzdUJOOXV3RjlUam5HbjVwbnd0LzgKLS0tIFAzZmZOa1dMaUxpbVc0MUhuMlJz
            emI5Zi9RRDg2eTlDNTJWU1dObDc2ZjQKXP6eo3dMjXzwomAncWSLqNGNVNlJxRmw
            btX2IW2HJXzsqvKJC0rE4XDxK8qDHneZGUJCkBMnLXqNZUxyOg9ScQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-16T06:26:15Z"
    mac: ENC[AES256_GCM,data:hUZXJ7rS3sqY8Z4tESr7by4FAT207LZhcFBCUPvPlK/P4uns3VtVIw0mE0JjT0VuOp73tH2IS4e2KS+VtsGdK7j8NSK6hPAirPuhujQvgLASHg8eEp6YB7TDvbH1a0J8MRc6nyhcaJPM+ltA8akW4GN5CmZR6X1v4ONyk/ZY7Cg=,iv:GXOUvcKi6Y5u6FsR9K/qTYXC/9y6W5JrXEyCO9t4xN0=,tag:CKKzcrqg/dVPqujwfdpQjg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
