# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:5ItawQjhOTYSsZFUR1w1jaonVrYJikOw/1C5h+nakEXs,iv:fOBqEqrPvIAGm3b/twENlX48cab4gWr3U6Ys9wm8WU4=,tag:QRKM7KuiLgCY07xaP1VbNw==,type:str]
    api-key: ENC[AES256_GCM,data:wkaGb5WzKe8v0ubpirxCfz+A/sbEQGXSoooLlpqJ7kKBap/sjQ==,iv:1/YcabWN+YWErVhwhUbkIfUr0YurIqZyZZ7pv31qyxw=,tag:PlKHE/0IdJa0b5QLL2wBpg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13y77gw9dk0ersm563x0caw9j5vaa0uglhrd0u48n6frdkxwh5eus05t6x9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnS3RZZnVCS0RvVmZFTGwz
            YWlxckVaU2hrYXhSS3owTXV4Ump5VWw4a0RvClg1KzFIMWZSdUFSR2dZSVZhS1JV
            Ui94RHIwSmN4SVZiQUtGL0ZpSjFTYTgKLS0tIGp0SWRIZzZobEpJVzcrL25WZ2F2
            NmgzdE5uTTVDSHBZT0N0eEc5RDFXYk0KkfLj/YHia29Hw01jQVXau49j428VccMa
            Z1e+lsW3vYsm8lggNHK6rkhRNRFycEgVH4GQ5Mb1AYeVB+TuLgco8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-16T06:26:15Z"
    mac: ENC[AES256_GCM,data:sa/VcAnVYIT1kj5jwUb6drvqnxYLtIg+LRLOAaDQLIOEQ/ZtvP+HIKI0GxR9turaLMHm+ZQCLsNRSiZeh2XoVj2hj0h7AuewQfCf13lHNBpD5+enTBpvX/jF/iuov5PoixMut32GgIY3x/ujMD7AxeNOz9G2KYTDBUlx+WiSz5M=,iv:S45PLyTetx9UASkqz09HBzWt3wm/qLVf37Zj7u5eHa8=,tag:zL2K/6FzNUVekyp0gkacUA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
