apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:tnaJaJ6tEw8g0TGLkUzX3ZG7uod2m2ECEt3/Q7U1jr+auKG7oWhs3A==,iv:qReskcjX4/WVUB2KnZ5bP7+iYfncwFM9ET4pmNhrYtk=,tag:FkK3KIHWed5O97SnBKUffA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mkv7d9mfplmlj46mxuvtzmfz2ds4q7620xszpu0vkzca6jjn3qcquck0cr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqcnBicUhFbjVLVDdrZWd0
            NHhnbnhHdDBPV2NvbGtmZGczbFAwbDNhczNrCkJ4STJVRCtYdEpPN1A0ZFhJNmh1
            OFVSV1ZaVkZVQzlZSjlsTmw0ZWdVMEUKLS0tIElBTWUzQnpCZE5XYnZWWU5zQ2ps
            cWo5Z3VEbVNmU1k2VnFQRzMvZVhJNmsK33MaPw/L+Du18fjHuaMrmZ+861rvMJ3a
            +98PWgH4cI0GSYEQ7mAlmZmSKj11F5WYQ0blOzDjKOHHMWzU/U+ZHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-23T01:15:50Z"
    mac: ENC[AES256_GCM,data:kRjI58HBzjwas+6LVkQ3PVFWKs+5ygzdGjfDMU2RvCZvBtuswl4fXRzURDMic5cgJL7ZHDD3nwIqPTbxMxd7LiT02SoIQQoKo0OCUT4vfECbWdkG0dDLs1rKo+UqP+N4GBqEPpgDBcXU9NwFX4aM+LlrKFHLE3mtObRL7fHBSjE=,iv:Ls2p2ouIJrB8InYOlWYvIC00sz0UpEoJRyStH/1Gd2E=,tag:tI2euaVlXMdkrbIIu48faA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
