# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:YhYWtUH0rK6HiZ9RJKHLM5BN,iv:9bfuGJtDsrrdSwYECP6NdBX6E/ODN4OjnvlpaqD/yIg=,tag:AcG2QXs2KTBLUkzvzIXtMg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:IMcSEBsFqOrx5sbBA33tPHhTBZZ51ySqT574+arGzM7/,iv:rrOvoLz/yKsSR+sk7LwwFyEx7z7TA0J6tgruKvKADWc=,tag:0sUvZYPbLjJcyLg/+p7Zfw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13y77gw9dk0ersm563x0caw9j5vaa0uglhrd0u48n6frdkxwh5eus05t6x9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHeURiUi9pekFNK1pxQkJk
            S3dVV1ZqMi96bGRrcTJ5WkU4czNRMGR4dTFVCnFVY3VUcDNySXpHQTZoUjdYdUp2
            cmNtMHdNRnBETzRrM0xSTEtNR2dPMDAKLS0tIHJtMkY0L01HK1F3dFpZNmYydlc0
            NUZQUW51TlFsc0cwaTNpM2pPM2Z5NU0KguGHvWwakSq1kUan2whFmdly48AAe3Ez
            HKjUhWsh1TrRqEvdge0N93L+pu8qXh+cQKW063yi0Aag82RVCCj6fQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-16T06:26:15Z"
    mac: ENC[AES256_GCM,data:anIhEPXwg6Imrk6ypzA0WPzVNzV7PUXAzTNXeYQkKrOMZyhhxBO/gNkqEkNJjAy/8hc3TCFWhoRSa6gmLvUQ8R2TWNcC6yg2YuIBLcy9vBPRzzBa1j3lvVtWx5cADFvIyQhk+cxHUtolzF9wR0V8qT2W6AcsVXWG8cQ1cgqocvs=,iv:8glDfgOJzUWZeHJ+B9+YFAOD5+J7dsG4dl4iU6CfVl4=,tag:GKDzVpzp3dpGT/JrgF3UwQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
