---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: echo
spec:
  components:
    - ../../../../components/gatus/external
  interval: 1h
  path: ./kubernetes/apps/network/echo/app
  postBuild:
    substitute:
      APP: echo
      GATUS_PATH: /healthz
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
