---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: memini
spec:
  chartRef:
    kind: OCIRepository
    name: memini
  interval: 1h
  values:
    controllers:
      main:
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1032
            runAsGroup: 100
            fsGroup: 100
            fsGroupChangePolicy: OnRootMismatch
        containers:
          main:
            env:
              MEMINI_API_KEYS_FILE: /etc/memini/api-keys.yaml
            resources:
              requests:
                cpu: 25m
                memory: 128Mi
              limits:
                memory: 512Mi
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
      api-keys:
        enabled: true
    route:
      main:
        enabled: true
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
      ui:
        enabled: true
        hostnames:
          - "{{ .Release.Name }}-ui.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
