apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:NJeV8E6q25wIjkjN6hlzCOEom7IA3WZ5CjBASs0ii9wUm6FM+2YEFA==,iv:K4ULgNnu8orSPhrL3uen0TMQXCTGPiNRUYMm5QszCng=,tag:cTpv2FZf8b41GqDgbvo7sQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mkv7d9mfplmlj46mxuvtzmfz2ds4q7620xszpu0vkzca6jjn3qcquck0cr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3YWhvMEVDa3FtOWFqTExn
            bnVZWDZFMUJobnVKWjR0bmZ3RTR3VTBxQ0IwCkVpZHlnZVVMSzVucXNPSEtmWkwy
            VFFSVzY1bXVST1VpVWhWT2RPcHU2eVEKLS0tIGdBKzk5UzRhbXRkVFFnMXhIZWI0
            aW5GMnVuOXUydnAzWTVqalZnaysvcG8KPonWXh9v5mt9Z/pFTjER125YcVsBakhq
            EJyNpuaOCmw68HzXQjfdA5mFy1qWHblTu31MH8W0eYCBfq/USk1Cdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-23T01:15:50Z"
    mac: ENC[AES256_GCM,data:Gbv7durcvZkl6PGf2oViTNsqfqa92x8Sytl/j8Hibmlh+EQBFQsZX81Bi02GD1z6ZUrXfI4nWwb7jJRYspEoMcEAnssefCuiXoWeaI7RFwZi8QDScPXei1oKtePQT9gRI67nM7+IGBFBkRN7d9aRcVVbCe7ZOYHLhnVhXWMaBHg=,iv:HrRYAi2r2cvZ+URDuuKpk0NbK9nk1kjEHGLBD3691VY=,tag:62Ltzoj4HTK43Y3Wkq4RuQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
