apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:YjiLbWANQeTKYwqDU02IZHq+6KU9t4gLk31D/LNVpzqtpn4kk9RNYg==,iv:38iQrrZsJERQ4Kyl6+Goq1wq12qdX2Gnt6pUqsdnfCw=,tag:PVrukyEz5vBte38xI7B6Rw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12pacd3s0eg20p7kd5459lflk8ahrw389um9zn7c5q3uexpny0phsqen4s3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyenRGdE1TSnFSM3hGU0RM
            ZzlSb1pvempuZThtSlQvQ0ZJUjAvNjV2UHcwCkhzNWdmb1JqdUhGemtqbUF6Mm5S
            QWlGYUIxQ3hkTWdELzFFSmxDSExKT1EKLS0tIEE0Nlp2QWN4UWVibm15TWdRWndw
            ZnNKaVVwdUVzY0g1a0lpVTBjKzUrRWMKEjqWofbUIOE3AA5tt3DtIqF8KqIkFJOt
            q+GQpn1n9kMFVAstBJYosDVLHfl8BbsybDA83q/+FV5H0rpJcuCzRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-15T21:34:15Z"
    mac: ENC[AES256_GCM,data:P47ntCMnrcqUC14q/O1bSgLdruWjdl7bbAt91bquuA2BJC8HgliWvFeqBL5K8kHkqpSu3KoOLPDryAcctmBJowvmnTE74QsAM5+Cm7gsj7sM7xD5a/eBH367K9cDHZueB3gTe6SLmiXBzkiR8pHpggBxJKyY18KZR067Vm7K5Wc=,iv:Vf36eDMBUuEwVPyHRu+r5PiBWoWF68K+8h2swCW0oDM=,tag:i2ppbb+/oEEvtp0FnFXFkw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
