apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:QpOjx5xQMS3qT7kAEJGSUkyadvOw0yHxnK7HKfN7ziXTcrX/UjuUxg==,iv:ZwKDh8Oa8l/47VV0cvUZ5Qq1W0tL4NRKEVnLFl1sruQ=,tag:SC32qHLj7S9Bknn933sAfw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12pacd3s0eg20p7kd5459lflk8ahrw389um9zn7c5q3uexpny0phsqen4s3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMzZmTGYzK3ZFMmpnSVFm
            ZDlyWXRJbGVwNzlXbVNxdXhUU2swUklUQmxnCkZEeGhRSmdVNk1ZMDB3UzEwMWJu
            OEQvSjlSMVd1aVNkRWxQZDg0TllPajAKLS0tIG9yVXVQQmZYbE95RmFSdm9iYlM5
            NWs5SnpHQzZxL1NJelZtclZxWDBVZVEKn3dIzv2NodQ7851S/O8oSsdUxngdlOBz
            xmmOTwRcOQrb0y7cBGqAGL52Cn39P68Vm4+d8aTcqP6PGTVuuo5neA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-12T01:02:59Z"
    mac: ENC[AES256_GCM,data:1F4eHS4Ye+Yno8Nt33c0KUO1ba9Bx6E7oDuS0q1jE6DZj6Wn03g1CY1wGpw1w4xgWtjXX75SCIZBlBL4EiVoxcSkPGE+bug108+D9web+s3jJ8ugqtADG0Q7trY9Y9kARdRaS43U1ots9fFLi1CZtlt/pfB9hPEra3Mn9Q9h1Xo=,iv:ecHRiSDF+rCxP2OrmF82lKtXAv6tq/hArT6+Zvt9jOo=,tag:3bdS6hm8qcDWQxJpG1x0eQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
