---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gatus
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: gatus-secret
    template:
      data:
        PUSHOVER_TOKEN: "{{ .GATUS_PUSHOVER_TOKEN }}"
        PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
  dataFrom:
    - extract:
        key: gatus
    - extract:
        key: pushover
