---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: gatus-rules
spec:
  groups:
    - name: gatus.rules
      rules:
        - alert: GatusEndpointDown
          expr: |
            sum(rate(gatus_results_total{group="external",success="false"}[1m])) by (group, name, type) / sum(rate(gatus_results_total{group="external"}[1m])) by (group, name, type) > 0
          for: 5m
          annotations:
            summary: >-
              The external Gatus endpoint {{ $labels.name }} is down or failing based on the failure rate.
          labels:
            severity: critical

        - alert: GatusEndpointExposed
          expr: |
            sum(rate(gatus_results_total{group="guarded",success="false"}[1m])) by (group, name, type) / sum(rate(gatus_results_total{group="guarded"}[1m])) by (group, name, type) > 0
          for: 5m
          annotations:
            summary: >-
              The guarded Gatus endpoint {{ $labels.name }} has a public DNS record and is exposed.
          labels:
            severity: critical
