---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr-se
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: radarr-se-secret
    template:
      data:
        RADARR__AUTH__APIKEY: "{{ .RADARR_SE_API_KEY }}"
  dataFrom:
    - extract:
        key: radarr-se
