---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${APP}"
spec:
  accessModes: ["${PVC_ACCESSMODES:=ReadWriteOnce}"]
  dataSourceRef:
    apiGroup: volsync.backube
    kind: ReplicationDestination
    name: "${APP}-dst"
  resources:
    requests:
      storage: "${PVC_CAPACITY:=5Gi}"
  storageClassName: "${PVC_STORAGECLASS:=ceph-block}"
