clusterName: production
talosVersion: v1.1.0
kubernetesVersion: v1.24.2
endpoint: https://10.0.0.88:6443
allowSchedulingOnMasters: true
cniConfig:
  name: custom
  urls:
    - https://raw.githubusercontent.com/alex-matthews/home-ops/main/infrastructure/talos/production/install.yaml
nodes:
  - hostname: master1
    ipAddress: 10.0.0.31
    controlPlane: true
    installDisk: /dev/nvme0n1
    nameservers:
      - 1.1.1.1
      - 8.8.8.8
    networkInterfaces:
      - interface: eth0
        addresses:
          - 10.0.0.31/24
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.0.1
        mtu: 0
        vip:
          ip: 10.0.0.88
  - hostname: master2
    ipAddress: 10.0.0.32
    controlPlane: true
    installDisk: /dev/nvme0n1
    nameservers:
      - 1.1.1.1
      - 8.8.8.8
    networkInterfaces:
      - interface: eth0
        addresses:
          - 10.0.0.32/24
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.0.1
        mtu: 0
        vip:
          ip: 10.0.0.88
  - hostname: master3
    ipAddress: 10.0.0.33
    controlPlane: true
    installDisk: /dev/nvme0n1
    nameservers:
      - 1.1.1.1
      - 8.8.8.8
    networkInterfaces:
      - interface: eth0
        addresses:
          - 10.0.0.43/24
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.0.1
        mtu: 0
        vip:
          ip: 10.0.0.88
  - hostname: worker1
    ipAddress: 10.0.0.41
    controlPlane: false
    installDisk: /dev/sda
    nameservers:
      - 1.1.1.1
      - 8.8.8.8
    networkInterfaces:
      - interface: eth0
        addresses:
          - 10.0.0.41/24
        mtu: 0
  - hostname: worker2
    ipAddress: 10.0.0.42
    controlPlane: false
    installDisk: /dev/sda
    nameservers:
      - 1.1.1.1
      - 8.8.8.8
    networkInterfaces:
      - interface: eno0
        addresses:
          - 10.0.0.42/24
        mtu: 0
controlPlane:
  inlinePatch:
    cluster:
      aescbcEncryptionSecret: ${aescbcEncryptionKey}
      aggregatorCA:
        crt: ${k8sAggregatorCert}
        key: ${k8sAggregatorCertKey}
      apiServer:
        admissionControl: []
        certSANs:
          - 10.0.0.88
          - prod-cluster.internal
        extraArgs:
          feature-gates: MixedProtocolLBService=true,EphemeralContainers=True
      ca:
        crt: ${clusterCert}
        key: ${clusterCertKey}
      controllerManager:
        extraArgs:
          feature-gates: MixedProtocolLBService=true,EphemeralContainers=True
      discovery:
        registries:
          service:
            disabled: true
      etcd:
        ca:
          crt: ${etcdCert}
          key: ${etcdCertKey}
      extraManifests:
        - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/v0.5.1/deploy/ha-install.yaml
      proxy:
        disabled: true
        extraArgs:
          feature-gates: MixedProtocolLBService=true,EphemeralContainers=True
      scheduler:
        extraArgs:
          feature-gates: MixedProtocolLBService=true,EphemeralContainers=True
      secret: ${clusterSecret}
      serviceAccount:
        key: ${k8sServiceAccountKey}
      token: ${clusterToken}
    machine:
      ca:
        crt: ${machineCert}
        key: ${machineCertKey}
      certSANs:
        - 10.0.0.88
        - prod-cluster.internal
      install:
        extraKernelArgs:
          - talos.logging.kernel=udp://10.45.0.2:6050/
      kubelet:
        extraArgs:
          feature-gates: GracefulNodeShutdown=true,MixedProtocolLBService=true
          rotate-server-certificates: "true"
      logging:
        destinations:
          - endpoint: udp://10.45.0.2:6051/
            format: json_lines
      network:
        extraHostEntries:
          - aliases:
              - prod-cluster.internal
            ip: 10.0.0.88
      time:
        disabled: false
        servers:
          - time.cloudflare.com
      token: ${machineToken}
worker:
  inlinePatch:
    cluster:
      aescbcEncryptionSecret: ${aescbcEncryptionKey}
      ca:
        crt: ${clusterCert}
        key: ${clusterCertKey}
      discovery:
        registries:
          service:
            disabled: true
      secret: ${clusterSecret}
      token: ${clusterToken}
    machine:
      ca:
        crt: ${machineCert}
        key: ${machineCertKey}
      certSANs:
        - 10.0.0.88
        - prod-cluster.internal
      install:
        extraKernelArgs:
          - talos.logging.kernel=udp://10.45.0.2:6050/
      kubelet:
        extraArgs:
          feature-gates: MixedProtocolLBService=true,EphemeralContainers=True
          rotate-server-certificates: "true"
      logging:
        destinations:
          - endpoint: udp://10.45.0.2:6051/
            format: json_lines
      network:
        extraHostEntries:
          - aliases:
              - prod-cluster.internal
            ip: 10.0.0.88
      sysctls:
        fs.inotify.max_user_instances: "8192"
        fs.inotify.max_user_watches: "1048576"
      time:
        disabled: false
        servers:
          - time.cloudflare.com
      token: ${machineToken}
