apiVersion: v1
kind: Secret
metadata:
    name: sops-age
stringData:
    age.agekey: ENC[AES256_GCM,data:ofzhrNwhvkdu1Gaz9N0IJcmp+dSmRH7ex7vcb+KLBV5Qn+i1WB6Gpi8nw6BW5LEj4+W8q3nn1pQKFjkvuD8PA11NjNQEB/wFO3yb,iv:/DNroYzWM7yyEEcP8OshSqJzlbVH9R1zmSx0OOxAsZQ=,tag:wstcRdkiUqS5FMtnWVjuPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vrlh74rr2ph4l7t07nhq0qmlwnm4ykckyhaf3teutxe437c6s4wsrf37mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGa2dTYU9tdkF5YXlMZVpo
            NDFkWnFoUlFGZHlXbmVWWlZJbWdWU2VubmhvCm10emtVSDE1aHZDT2lwcXJIR1k1
            cHRhZUdOdTEwTW5UdGFzcUt6dkFCajgKLS0tIExVekk5NXI1V08zbnQvdDZtV2d3
            eEZvNmNmSHhSa2FzdGFiclBMT2xVVHcKJlAETyviLT50tZ9WyPGerP/JLuMksN+o
            WC40mb16UVsaODumNLnwQ3xU35Y/j6gh2DcLLn8PxpOLuL8CjovXbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-05T04:11:27Z"
    mac: ENC[AES256_GCM,data:BzqyQMICSJe23AZAWOms7czjnkH87nzKiYrzZBcO8thvM95KVugUncr5y0xvE4z0g48x0YlQXskHWaFfsU03JFcS5fo7hD0Yyo/46p3HCNczStYUVa1pc/rxUPX6VK22rY4caveflfT2uViuJA5Vy3c2MXE4ZEr4U24l3jGhvJ8=,iv:h5XHBOuBFsBpqGxKbzMN4DckkJehVZUT4x/CM9p9cMg=,tag:F1T0Y9qFIhxJ3LuRRbV6Qg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
