---
# Note: Gatus vars should be escaped with $${VAR_NAME} to avoid interpolation by Flux
# Fix: https://github.com/onedr0p/home-ops/commit/f6bbef667b69d218101ba3d18fe1a810527378d3
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m

endpoints:
  - name: cloudflare
    group: connectivity
    url: icmp://1.1.1.1
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: google
    group: connectivity
    url: icmp://8.8.8.8
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: quad9
    group: connectivity
    url: icmp://9.9.9.9
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

metrics: true

storage:
  type: sqlite
  caching: true
  path: $${GATUS_CONFIG_PATH}/gatus.db

ui:
  title: Status | Gatus
  header: Status
  logo: https://avatars.githubusercontent.com/u/96397723
  link: https://github.com/alex-matthews
  buttons:
    - name: GitHub
      link: https://github.com/alex-matthews
    - name: Homelab
      link: https://github.com/alex-matthews/home-ops

web:
  port: $${GATUS_WEB_PORT}
