---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cert-manager
  annotations:
    home-ops/chart-verify-exclusion-reason: verifier-gap
    home-ops/chart-verify-key-fingerprint: sha256:20a9d8524b982644a958d6a301dcc9296671bc76e924334f28cd7231d8f2e8fa
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v1.21.2
  url: oci://quay.io/jetstack/charts/cert-manager
