---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: hermes-secret
    template:
      data:
        LITELLM_MASTER_KEY: "{{ .LITELLM_MASTER_KEY }}"
        MINIMAX_API_KEY: "{{ .MINIMAX_API_KEY }}"
  data:
    - secretKey: LITELLM_MASTER_KEY
      remoteRef:
        key: litellm
        property: LITELLM_MASTER_KEY
  dataFrom:
    - extract:
        key: hermes
