apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:ZKVns5l3k3aYH5nHXyR8Yg==,iv:4OUcNiAJSKekvWM8KLjuxwWrBVZ+3jxBHcw0+/b5hIU=,tag:+UgYz63y+NJowd1BdyN8Eg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:cluCyj/Y08+S9aXZf7IwrglHOOcqzps=,iv:3FmaiNpZ5bDU/OXfClrWKX4Mlv/GExgoylwcfWxaalI=,tag:QpdXm2tm7HPGnokzjAlhEQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:tphHsUd6fwVELfGIhtBRb208rF3JpGwicmRi1hyYkohUS3Fu,iv:isZky3wzG2Imqrx7EUHfrLJPU7Y13uEtRGdyhfiF9eQ=,tag:/pwVWHb6jstU4QHv0CizMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mkv7d9mfplmlj46mxuvtzmfz2ds4q7620xszpu0vkzca6jjn3qcquck0cr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpVUpNdWFIUTZBSGtpNnNv
            V3dVN0piTXphUVR2QW9STldhR002K0dsU1MwCm9vOGZtS25XVElZT05YTlI2c0s2
            czA5YTlQQlhUUGhPY2FBWHEwWDFSKzgKLS0tIDZHNnZIWkVZUTRJNmtLYjBJSDlw
            UDl0OHltclBOZ1pBR1JXU0Jqa2NmeWsKRUrJYZnshDPL8ydTD0dEwYHkjJHkDpDq
            Hm56/sbceJxRFD67vcQ8jcPHc8DxxnuqeWeL8oxL6H0y1hCa/nRwZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-23T01:15:50Z"
    mac: ENC[AES256_GCM,data:SRgvzXOycHawvYqltcK7nXztI9ai/qu7CqRow9/NF980yqSnhMVU6ECDxekCV1bKfqGsepQ0D80r9n0UtxfnQIPb/p4nbeX9ymLWGv4/N1K38AYpFrunCKNcBCIWdmU8hGKqDZExHf2CwWVO35CPqwbQUGi8/ZDSl/x4yiNdvoA=,iv:IrDnKllJlhJsb0REEHzBdU+A33io+RtQ/KW0hVVPpYc=,tag:6OraYJi6d14muMNYxNIhtA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
