apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:hXXbGnZZZNNZhFtQnska4dDFwoWzhFu6+wTyK+XPoeZtyt1q4crHDy1v5C+qCfJLBKXTodEc35KFJ9LCeLMsi9XMpl4zwIgzJYHVCogR9AhWmKvxwtaFqBiXM0PMhw==,iv:s8H6aLCWjhDJodnCN3UnE3lxuLMlAhnCYCt1oQlttHU=,tag:bJYL2d2yrN6gPQ1pqg0u5Q==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:ETutWoAjxvLQpG6wvgmNFw==,iv:ELvQlnwnPmtZ+biMLmGErEBeBdS+G1I//w5hIWvMXhQ=,tag:7wktVXQX9wE1EwnP/OeUfA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:iArDNkVVSCfiE1M4sdVRjLQVFaZBiQY=,iv:eyIz0d/BfCbXz+XEy1Nik3k19QVMBum8TFCVs9l+WuE=,tag:wwgHFyKwzr1c7UbZMw2bhA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:MI6VdHmQlFFx9HtowdFjz70BP/DeQ8/XuPwDquRoNJvZ+bIH,iv:BHqsshRzVlANmnq4lsewjbzkbnqurc/lXa1ciAT50WU=,tag:xejkiPEGzcs0tv6rp7Ujug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12pacd3s0eg20p7kd5459lflk8ahrw389um9zn7c5q3uexpny0phsqen4s3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxd2Q2dmlLa0pxZUhPWUNZ
            d3ROcFZsbHJUV3pKQjBieEpMTWVoTEF1czM0CkpsR093RjFncUlvVitOZmdGajZR
            UzVSRmFHa1R3ZDU3bFVGamZXYWt0REkKLS0tIGxmajFteUwyRys0SE8xRnVDMXFH
            R25uN3NCN2toMUFWeWJVYXNaM3V2ZFUKpwHhS2vJaX/5LlagrCX/9ovNkzhy74hO
            R59Cv7Vtf7p1Ao2X5fWLeSj+lZPlLd93hJG3KbbIKdNDnFL8ZK56Ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-05T05:05:40Z"
    mac: ENC[AES256_GCM,data:eeX5/p5dZH0AaZ0/C62ONuwg2lRtZUTK5i6RMWh6efqgmRXTElnU7ZlW3BnfJky/q2I0i4ItQ1xWpDE82cckQw/phgIA8Z8mvSVcLODGkO0q9QXQSr+PVqIjWWXu5MMKvPinC1EBwpG6bep+Ef3rJsTle6xtdvec9fLykKT5qn0=,iv:WjTwPpN839xCgIkj3aU+c/D2qYk2XHgr9+8sMUdG3P0=,tag:LPql7bhP8MUGN7iV9KBrMg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
