apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:smITzHZ35Q2rzzhByKeu/2KKNTB+6c1bPOXixN1BRVwJc+xu9HJ6kV4MVUiq/h6NoRxManf66pIItyUsVXKOjd+lzzOGGKrjzpx/gDD5g2iWnUqhLWdXkROCODle8A==,iv:9tOq0OXiuslIARqrOesnAyP4euXKaV9HZoo0e8pcobo=,tag:mxir6oxUnzCdaGNtkzNzaQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:psigxmTgVEWMhvdnKYhxHw==,iv:E1yCUZCEzkUMtUvvWj4srEHdACqq0vj2Ymp0Z+07tUE=,tag:TM3catv9BSlSg1OWjEhItw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:QZL960F04LAqCIZBa6ysGA31Z0dSlws=,iv:ZoQ+QtaVax/A1PmvJoXuyZwlPDE0LIS324npaD4S1GA=,tag:+kOWJxlGiu6OeOsrYWyylw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:xbyr8dSYwX4ODj1GBzrU319Kg2za06qgCyw29+MIe6oJJ0F5,iv:JeyURViUnUn8no8xqLjL5hUbaKZi/iC34giPSUOglv4=,tag:2PfWTaHEuu+ynShTW6QATQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12pacd3s0eg20p7kd5459lflk8ahrw389um9zn7c5q3uexpny0phsqen4s3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1dlgvR3lTWkZ5b2pkSEdi
            RkR0NCs4YkZUK3BkUG1vME9Lb1FwVkNJN1NrClBzcDNiZTNUbnY3MXFJTVNraXdN
            RmFLWElYNXdzTHhOVm1zQ3RWcERNSDAKLS0tIHZhZTcvMVBPemttQzdhYkxhNEFO
            T242SGFqNXo5OXJnRUltc0ZQdWJnMW8K13owcwI9McPYeWyJvU2urTK/n/9R1sAw
            lqJZV2iQW2ovvQ8JajOxet+/f8QcRUlgVKW/PDzt/jAJTfK4mByMEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-12T01:02:58Z"
    mac: ENC[AES256_GCM,data:mL1wEU9KLRFbN4hzV4Wvpmm0ZI6AI2xnR/BW7EA7UXkSsnVQq4iBcEUcRgTcf67YOC1oZ1JlvtAWN7LjHG8hXB0hW5WMpu9/tYqiv9zsyn3U1IXoo9NVUbfwomRHW58eagPszp/yetmQyw5Ctl/f13B5moeyD3q7Xsu8YHby8ME=,iv:5DwaavhySdQ/N7JL8v+Z4feankifO+8OjbRM1Hbcifg=,tag://njJLMpu6fKcfSDOFyVdw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
