---
ingress:
  - hostname: "*.${SECRET_DOMAIN}"
    originRequest:
      originServerName: external.${SECRET_DOMAIN}
    service: https://envoy-external.network.svc.cluster.local

  - service: http_status:404
