---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: internal-external-dns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: internal-external-dns-secret
    template:
      data:
        UNIFI_API_KEY: "{{ .UNIFI_API_KEY }}"
  dataFrom:
    - extract:
        key: unifi
