---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: smartctl-exporter-rules
spec:
  groups:
    - name: smartctl-exporter.rules
      rules:
        - alert: SmartDeviceHighTemperature
          expr: |
            smartctl_device_temperature{temperature_type="current"} > 65
          for: 5m
          annotations:
            summary: >-
              Drive {{ $labels.device }} on {{ $labels.instance }} has exceeded 65°C.
          labels:
            severity: critical

        - alert: SmartDeviceTestFailed
          expr: |
            (smartctl_device_smart_status == 0 or smartctl_device_status == 0)
          for: 5m
          annotations:
            summary: >-
              SMART test failed for drive {{ $labels.device }} on {{ $labels.instance }}.
          labels:
            severity: critical

        - alert: SmartDeviceCriticalWarning
          expr: |
            smartctl_device_critical_warning != 0
          for: 5m
          annotations:
            summary: >-
              Drive {{ $labels.device }} on {{ $labels.instance }} has a SMART critical warning.
          labels:
            severity: critical

        - alert: SmartDeviceMediaErrors
          expr: |
            smartctl_device_media_errors != 0
          for: 5m
          annotations:
            summary: >-
              Drive {{ $labels.device }} on {{ $labels.instance }} has reported media errors.
          labels:
            severity: critical

        - alert: SmartDeviceAvailableSpareUnderThreshold
          expr: |
            smartctl_device_available_spare_threshold > smartctl_device_available_spare
          for: 5m
          annotations:
            summary: >-
              Drive {{ $labels.device }} on {{ $labels.instance }} has low available spare capacity.
          labels:
            severity: critical

        - alert: SmartDeviceInterfaceSlow
          expr: |
            smartctl_device_interface_speed{speed_type="current"} < (smartctl_device_interface_speed{speed_type="max"} * 0.9)
          for: 5m
          annotations:
            summary: >-
              Drive {{ $labels.device }} on {{ $labels.instance }} has a slower interface speed than expected.
          labels:
            severity: critical
