---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr-uhd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: sonarr-uhd-secret
    template:
      data:
        SONARR__AUTH__APIKEY: "{{ .SONARR_UHD_API_KEY }}"
  dataFrom:
    - extract:
        key: sonarr-uhd
