---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: snmp-exporter
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: snmp-exporter-secret
    template:
      data:
        SNMP_AUTH_PASSWORD: "{{ .SNMP_AUTH_PASSWORD }}"
        SNMP_PRIV_PASSWORD: "{{ .SNMP_PRIV_PASSWORD }}"
        SNMP_USERNAME: "{{ .SNMP_USERNAME }}"
  dataFrom:
    - extract:
        key: synology-snmp
