---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app snmp-exporter
spec:
  chartRef:
    kind: OCIRepository
    name: snmp-exporter
  interval: 1h
  values:
    fullnameOverride: *app
    config: |-
      auths:
        synology_v3:
          version: 3
          security_level: authPriv
          username: ${SNMP_USERNAME}
          password: ${SNMP_AUTH_PASSWORD}
          auth_protocol: SHA
          priv_protocol: AES
          priv_password: ${SNMP_PRIV_PASSWORD}
    extraArgs:
      - --config.file=/etc/snmp_exporter/snmp.yml
      - --config.expand-environment-variables
    envFrom:
      - secretRef:
          name: snmp-exporter-secret
    serviceMonitor:
      enabled: true
      params:
        - name: nas
          module:
            - synology
          target: nas.internal
          auth:
            - synology_v3
      scrapeTimeout: 10s
      relabelings:
        - sourceLabels:
            - __param_target
          targetLabel: instance
