apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:usKqFXHIC/2SxCkkEK+XvuH0zWEj+IOKdcj4cljRAOw=,iv:jYFnDqffmOUbgTtG56Q2m9FamI7M3xZ+D16muMBw4Hk=,tag:LwaERRpCj75KZZzXdDL42Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mkv7d9mfplmlj46mxuvtzmfz2ds4q7620xszpu0vkzca6jjn3qcquck0cr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZXBQblBwUk4waFBheE5P
            V0tESFJiZXAxeEtMRzdHTEE4Um05RXl5SzBFCjkrVXl2MExPUFRSWVNkRWt5QVlK
            U1lySnNlNmIvcG15em0zN0dkUnlia2sKLS0tIHlFMlRwdjdnUW1HZ2tmeW5kMUZv
            dC9SQWgrSFprSkRQNFRmVktrRS9LY2MKtqvCE9AvV//6ITfhdtwceWSzjj9hpRQM
            CiAK8KTijzckPDo7ZdD8Sx3i6Uxwi3i3wVb3jDX7WtZvhoflJyWTig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-23T01:15:50Z"
    mac: ENC[AES256_GCM,data:04jj5gXm1tgG+e3Y+PXkKzI1pS50D4xvAlX/Wf0GK1AaBDZivBOGmuSuOa/J+z7McutDc5bdhJMM6jXpMv3SED3j56XXU9I0LUW6zQdrsbblvy6+rPOYPGajRX4ylOov6D8RrR+Tx0wswJJ/kNCw1vvuzOoJlRsMq7AMAaa4nSo=,iv:YLFtyZS5qtowYxsRNYS+4y97YcqkMx6WNR88ABcBPy0=,tag:yJTs4ZfALYlFcQR4qcPKOQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
