apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:KUNRCcOyrqm2mRFrNmCTbZ6EW3+J//j9D+oUV/rGvK4=,iv:0lMY4mCcpPuDeSGYaGBP9kJNqZlxOxOId4mshaMVckk=,tag:omyx+7hzX6WcsV2MVEqfzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12pacd3s0eg20p7kd5459lflk8ahrw389um9zn7c5q3uexpny0phsqen4s3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjdUJrOHpuVURub2xQMlVC
            Tlk1TzJVZDI4WktKaUJ1alJVY2ZMMTkvWFdrCmZMOXJPcFFxaEhDd3d0Y2NteTR6
            VVBLUlh1dVhsMnZuRHZEdXdmam1jdlEKLS0tIDU1RW9PRHkrdzliY2hYMnJjRnd2
            dUxKOEk1L3JIODh3SmNWdzhySFhNb1UKlbseV0LxsGz4lEBCoHyLPeh0+5A7Qr/o
            tnitbLce7mL1Zq7VARKt7bwsj4xfQJ//i8K0Pv/D604QUuEPvZ2miw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-12T01:02:59Z"
    mac: ENC[AES256_GCM,data:6IJJqfKBbDofh/pciRZ6GH9s2aWsLCvc+lrKm5PKk9VgRAgSf47fTraQapAxJXz4/hvfhcZe88T1CZhBK7fpvsT/4R3habfqbQ1+mogUk1is/1CE5ApzXsWy0RzUANatJGMVVrUHffGp2oKATifwKqOANBd2NOyObFiZxVpq04M=,iv:W8C1apbPiCM+UW5GlmfRoBUv+rPjWTScI3qhcwZ88ms=,tag:XSkTA1UmfPjAAZ/LkBdTwA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
