---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: recyclarr-configmap
    files:
      # - recyclarr.yml=./resources/recyclarr.yml
      - ./resources/radarr.yml
      - ./resources/radarr-se.yml
      - ./resources/sonarr.yml
      - ./resources/sonarr-uhd.yml
generatorOptions:
  disableNameSuffixHash: true
