---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: litellm-db
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: litellm
        password: "{{ .password }}"
  dataFrom:
    - extract:
        key: litellm-db
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/databaserole_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: litellm
spec:
  cluster:
    name: postgres
  name: litellm
  login: true
  passwordSecret:
    name: litellm-db
  databaseRoleReclaimPolicy: retain
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: litellm
spec:
  cluster:
    name: postgres
  name: litellm
  owner: litellm
  databaseReclaimPolicy: retain
