---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: memini-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: memini-db
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: memini
        password: "{{ .DB_PASSWORD }}"
  dataFrom:
    - extract:
        key: memini
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/databaserole_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: memini
spec:
  cluster:
    name: postgres
  name: memini
  login: true
  passwordSecret:
    name: memini-db
  databaseRoleReclaimPolicy: retain
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: memini
spec:
  cluster:
    name: postgres
  name: memini
  owner: memini
  databaseReclaimPolicy: retain
  extensions:
    - name: vector
      ensure: present
    - name: vchord
      ensure: present
