# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:scgRKlR8J4mZMbC6WNRtWw4d13dpT3GcEbVB1wTUESyA62yKssgeFQ==,iv:gAdUQyrtpcv31/FGLfoWepEVcLqUdcnpYnXJ/cRBE3c=,tag:ERNgqpMXvmXvenUWm5LKJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13y77gw9dk0ersm563x0caw9j5vaa0uglhrd0u48n6frdkxwh5eus05t6x9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuNGRNN2pHbldaTWdlcjFO
            bFVaKy9vMFBLWGk3RFJHVVFKZGtnb3hzV3hFCjZ5ZWIxMFRsQXFtWmp0QnlCYmJz
            d3VsZGRiR2NoeUVyMHhwSHJrak0vNm8KLS0tIFFBZ3Zva1dkMExIbkdhQ0dNZTlt
            aTVOSXRkSmRRYmFxeWU2WVpEK2QxU1EKlGfCj7n8/FxMemTPrpCK1DIcPC73xhCZ
            HdsOp3BxR4lFj7pgiEqSAy9PpECqfOxsdAOmdR1NByjAzMQMeSzhwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-16T06:26:16Z"
    mac: ENC[AES256_GCM,data:LiT0MNh36562PIxHDQJ7zGjasKvdTq3JxdzeK0xjWnPnrllgG+4EO6gv8eKagJSpAEcmBHGHqdP4zSgh5+DbX8RTEdzbsrc463BOz+QAMG5LvIvZiZhXCppagQeDrBCwAqauoLwJJfpVLzmqp9imAXh99vyo8DJHbsY1KPlTI8U=,iv:DlyXJkMylTfffCc2TlCBxY48ln8hMZFQreJN5rPuzaI=,tag:HkHrqrtU1V8aLQe1nvw2RA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
