apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:efWF8KPk+t043uVNf5KvYNKXK4SyvnebbsWXq6fODOZ8vxRgcQYtBQ==,iv:MmkmB371LWYeVGR94QNhIIwuk2bDxnjEIZJCzCpid+Y=,tag:fhxQj//VXCcHvrt3Zm7bdg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12pacd3s0eg20p7kd5459lflk8ahrw389um9zn7c5q3uexpny0phsqen4s3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTHljb0tCOVBmWWx6MHFE
            ZEFFRFNVOXFIbUZBWjc4Njh5RTR6clFiQmhvCnBmQU9KYm1Qb01DNFpGdnBFSnpQ
            bHJqZW83QkFoTklkQWQwNkY0V0ROamcKLS0tIHNEZ2RUVDdUOXhTRm00UDY2ZGFS
            ZUE3dkpLQUpjVkFvSndNTm1MaFU0R0kK/wA6MSW9Og3/f+Vs0Zg4//r5tcKDXusk
            sXqobVzn7i1sYM4yvzbcy2c+Ph0iPtHDP/rZLqoC0NOEJ+3T4yOQog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-28T05:21:05Z"
    mac: ENC[AES256_GCM,data:ZZagmmMLSSLLjJ8dms5z0c5VhTTiQ5ulGIh/E1CP1TLjlYHTUo/5kApfMOycsLZ8/+TdFE6EJAUOlfzvwW2pv61n8+elsmjaUIFLbvl1F4ODFWf7kkWXiKTmvHx3eY8WfeaEOr7J7+9YMqvJbF4d/Kl76bG3USffivxKJvlfX8Y=,iv:NMtMpK7uvMbMxSnaob4jQ5mNluM4jBLJf3e0tL8k97c=,tag:kK63L6k0PxhWjYGVQjCqmg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
