apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:IL2yP1S16/0aV2fVo7/mJyDuChteGocyi+wnYqX9yUqtH892ma2wJQ==,iv:AN6RUJFUcFsZiNpRMaZB9kMOEj2y/ADMueMV6rESvvY=,tag:n9N6uf+4fguZ9PNw+fyxAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12pacd3s0eg20p7kd5459lflk8ahrw389um9zn7c5q3uexpny0phsqen4s3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTHljb0tCOVBmWWx6MHFE
            ZEFFRFNVOXFIbUZBWjc4Njh5RTR6clFiQmhvCnBmQU9KYm1Qb01DNFpGdnBFSnpQ
            bHJqZW83QkFoTklkQWQwNkY0V0ROamcKLS0tIHNEZ2RUVDdUOXhTRm00UDY2ZGFS
            ZUE3dkpLQUpjVkFvSndNTm1MaFU0R0kK/wA6MSW9Og3/f+Vs0Zg4//r5tcKDXusk
            sXqobVzn7i1sYM4yvzbcy2c+Ph0iPtHDP/rZLqoC0NOEJ+3T4yOQog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-12T01:02:59Z"
    mac: ENC[AES256_GCM,data:mngQhBqYmUvT2eii8KrTorVhiIKCfHnE4JJbnz74D7LF3LkHY2mMnilhhXy4HNc9hM4UHLkeuXKP6En+EdindPL8n3N/37whZJCsTVLWZYZimjMg8Kq/uNVMUP+D/RlSXEQ8Mpa7ihhJa34dimh5pTkdAJ/UvFovdTnEQxwy26s=,iv:5stgdx/UzErlJ19vyW3p9OhJSG4HwcnrdUb+v1IYx+c=,tag:6Bch4Bt+otVNf+pOfPH1xA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
