---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: grafana
spec:
  image: docker.io/grafana/mcp-grafana:0.17.1@sha256:d4e0044c0efbbd00a004871a8e679f990b57a7fa21b69a51357737ddbe9d57af
  transport: streamable-http
  proxyPort: 8080
  mcpPort: 8000
  args:
    - -t
    - streamable-http
    - --address
    - 0.0.0.0:8000
    - --disable-admin
    - --disable-incident
    - --disable-oncall
    - --disable-provisioning
    - --disable-rendering
    - --disable-sift
    - --disable-write
  env:
    - name: GRAFANA_URL
      value: http://grafana-service.observability.svc.cluster.local:3000
  secrets:
    - name: grafana-mcp-secret
      key: GRAFANA_SERVICE_ACCOUNT_TOKEN
      targetEnvName: GRAFANA_SERVICE_ACCOUNT_TOKEN
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi
  toolConfigRef:
    name: grafana
  groupRef:
    name: mcp-tools
