---
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
radarr:
  sqp-5:
    base_url: http://radarr-se.default.svc.cluster.local
    api_key: !env_var RADARR_SE_API_KEY
    delete_old_custom_formats: true
    replace_existing_custom_formats: true
    include:
      - template: radarr-quality-definition-sqp-uhd
      - template: radarr-quality-profile-sqp-5
      - template: radarr-custom-formats-sqp-5
    custom_formats:
      # Preferred movie versions
      - trash_ids:
          - 0f12c086e289cf966fa5948eac571f44 # Hybrid
          - 570bc9ebecd92723d2d21500f4be314c # Remaster
          - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
          - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
          - 9d27d9d2181838f76dee150882bdc58c # Masters of Cinema
        assign_scores_to:
          - name: SQP-5
      # Preferred HDR formats
      - trash_ids:
          - f700d29429c023a5734505e77daeaea7 # DV (Disk)
          - b337d6812e06c200ec9a2d3cfa9d20a7 # DV Boost
          - caa37d0df9c348912df1fb1d88f9273a # HDR10+ Boost
        assign_scores_to:
          - name: SQP-5
      # Unwanted
      - trash_ids:
          - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
          - cc444569854e9de0b084ab2b8b1532b2 # Black and White Editions
          - 923b6abef9b17f937fab56cfcf89e1f1 # DV (w/o HDR fallback)
          - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
          - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
          - f537cf427b64c38c8e36298f657e4828 # Scene
          - 9c38ebb7384dada637be8899efa68e6f # SDR
          - 2899d84dc9372de3408e6d8cc18e9666 # x264
        assign_scores_to:
          - name: SQP-5
    media_naming:
      folder: default
      movie:
        rename: true
        standard: p2p-scene
