---
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
sonarr:
  web-2160p-v4:
    base_url: http://sonarr-uhd.default.svc.cluster.local
    api_key: !env_var SONARR_UHD_API_KEY
    delete_old_custom_formats: true
    replace_existing_custom_formats: true
    include:
      - template: sonarr-quality-definition-series
      - template: sonarr-v4-quality-profile-web-2160p
      - template: sonarr-v4-custom-formats-web-2160p
    custom_formats:
      # Preferred HDR formats
      - trash_ids:
          - 7c3a61a9c6cb04f52f1544be6d44a026 # DV Boost
          - 0c4b99df9206d2cfac3c05ab897dd62a # HDR10+ Boost
        assign_scores_to:
          - name: WEB-2160p
      # Unwanted
      - trash_ids:
          - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          - 9b27ab6498ec0f31a3353992e19434ca # DV (w/o HDR fallback)
          - ae575f95ab639ba5d15f663bf019e3e8 # Language: Not Original
          - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
          - 06d66ab109d4d2eddb2794d21526d140 # Retags
          - 1b3994c551cbb92a2c781af061f4ab44 # Scene
          - 2016d1676f5ee13a5b7257ff86ac9a93 # SDR
        assign_scores_to:
          - name: WEB-2160p
    media_naming:
      series: plex-tvdb
      season: default
      episodes:
        rename: true
        standard: default
        daily: default
        anime: default
