---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Render

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - kubernetes/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  render:
    name: Render
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Mise
        uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1
        with:
          cache: false
          install_args: github:home-operations/flate

      - name: Render cluster
        run: mise exec -- flate test all -p ./kubernetes/flux/cluster --allow-missing-secrets
